ФП-14
anastasiaelis/java-share pull request #1
Opened 2024-07-29 07:10 UTC by anastasiaelis

2024-07-29 13:34 UTC, anastasiaelis commented
никак не могу избавиться от ошибок

java: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'
java: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'

2024-07-30 03:54 UTC, VadimZharkov commented on pom.xml
Понижать версии не надо, не помогло ведь)
Интернет пишет что возможная проблема в версии lombok по умолчанию и предлагает задать ее принудительно (1.18.30)
https://stackoverflow.com/questions/77171270/compilation-error-after-upgrading-to-jdk-21-nosuchfielderror-jcimport-does-n
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.30</version> <!-- Added -->
        </dependency>

2024-07-30 04:06 UTC, anastasiaelis commented on pom.xml
Помогло! спасибо! дальше можешь пока не смотреть

2024-07-30 04:14 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +public interface ItemRequestRepository extends JpaRepository<ItemRequest, Long> {
В след. спринте работа с БД будет, но оставляй раз уж сделано.

2024-07-30 04:17 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        return new BookingDtoOut(
Программисты на java любят использовать паттерн builder. https://www.baeldung.com/java-builder-pattern
Тем более, что реализовать его просто с помощью аннотации lombok `@Builder`
В классах с количеством полей условно > 3 имеет смысл его использовать.
В мапперах самое место для использования данного паттерна.

2024-07-30 04:27 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @Autowired
` @Autowired` для полей на данный момент является "не современным". Предпочтительней является внедрение зависимостей через конструктор.
Поэтому  `@Autowired` убираем, на класс навешиваем `@AllArgConstructor` и к полю добавляем final.

2024-07-30 04:30 UTC, VadimZharkov requested changes
Можно улучшить

2024-07-30 05:00 UTC, anastasiaelis commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @Autowired
+

2024-07-30 07:19 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private Booking validateBookingDetails(Long userId, Long bookingId, Integer number) {
Передавать в метод и далее в нем использовать "магические" номера (1 и 2) - плохая практика.
Т.к. варианта всего два, то лучше использовать boolean и параметр метода назвать так, чтобы было понятно. number вообще ничего не говорит значимого.

2024-07-30 07:21 UTC, VadimZharkov requested changes
Нужно убрать "магические" цифры

2024-07-30 10:29 UTC, anastasiaelis commented
убрала

2024-07-30 10:39 UTC, VadimZharkov approved these changes

2024-07-30 10:49 UTC, merged